### ISSUE TITLE
Auto Backup Times

### ISSUE THREAD

**Issue by k-304** [SnipeLike/WinBackupper#25]
Hi @T0mH4rr1s0n 
So I had a look at your newest PR and I found some more bugs.
1) My Test Path is 2 lines long... so is it possible to highlight both lines when klicking anywhere on the path?
2) In this examble from above. When I want to set a time like Monday 10:00 I still have to set it like 2 Times. The Reset function seems also to be a bit buggy. In this case, I pressed the Reset Button, in the first Time-Form it seems to work, but in the 2nd and in the 3rd were still my old entry visible.

I'm shure you can find all this bugs also on your PC. Try a longer path and play with the highlighting function...

Have a nice 1 nd see u next week.

**Comment by MrCryptoT** [comment]
Thx 4 feedback will have a look at it... 
mhm... the first one is a good one :$ will try some things... (maybe only show the last few chars of the whole string?) Im sure we ll find a workaround ^^ 
Have u saved after the reset button? (I know i ll change it that it autosaves when reseting - currently it doesnt)
Do you only have 1 folderpair? Then its a bug that you have to set it two times ... (Or do u have 3 pairs and with timeform you actually mean the timeform called for each pair ^^?)Im sure ill be able to reproduce them =) just have to create a bigger test folder =)
I ll play around and see if i can find what u described in 2) ...see you

**Comment by k-304** [comment]
I had always only 1 folder pair /Desktop/Source and .../Backup
Yea take your time... Hope we can find a good sulution. I'm thinking about
it and will let you know if I have a briliant idea^^

Tom notifications@github.com schrieb am Di., 23. Juni 2015 um 21:20 Uhr:

**Comment by MrCryptoT** [comment]
Alright =) 
Hear you ^^

Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: SnipeLike notifications@github.com 
Datum: 23.06.2015  22:01  (GMT+01:00) 
An: SnipeLike/WinBackupper WinBackupper@noreply.github.com 
Cc: Tom tom.harrison@hotmail.ch 
Betreff: Re: [WinBackupper] Auto Backup Times (#25) 

I had always only 1 folder pair /Desktop/Source and .../Backup

Yea take your time... Hope we can find a good sulution. I'm thinking about

it and will let you know if I have a briliant idea^^

Tom notifications@github.com schrieb am Di., 23. Juni 2015 um 21:20 Uhr:

**Comment by MrCryptoT** [comment]
Alright I thought about it.... 
Following proposal =>
1) for Now - temporarily fix it by only showing the last X chars of the paths' that each one only takes 1 line
2)if that looks terrible (which I think it will) then I ll change the Function which highlights text, to highlight based on charlength instead of a single line. (it will check how many chars there are, check for each char on which line it's on, and then mark all of those lines... ) easily said,it will compare with the path's in the Arrays if the clicked Line contains all of the needed chars, if not it will mark it and check the next line... 
Now, if you click on Line 2, we can't assume that it's the second Entry (cause it could be the second line of entry 1) ...
So I guess we always have to Loop through all Lines - and check based on the content which entry it is... 
(Damn My head explodes already just by writing that)
I'll explain it in School.... I think we should decide or figure out the solution togheter... (cause my idea would be damn complicated - maybe I'm thinking to far ^^)
Have a good one Mate - maybe I have some better thoughts on the weekend.
EDIT: (I'll draw some diagrams how I could Imagine it to work so I can show them in School)

**Comment by k-304** [comment]
Yea that sounds very complicated... There must be a way which isn't so hard to think about it and to code it later on... Maybe the weekend has some good effects on us :D
Gonna think about it as well.
Have a nice weekend...
see u mondays

**Comment by MrCryptoT** [comment]
I think that's the easiest way ( I just written it complicated as hell xD)
![image](https://cloud.githubusercontent.com/assets/8693733/8382806/b35654fa-1c35-11e5-8ee3-290fd3f7a3e2.png)
Maybe you understand the flowchart - either way we have to discuss that mondays =)

**Comment by MrCryptoT** [comment]
I'll have a look at "Listview" Controls in VB.net 
Maybe it solves the Problem for us. (I think it handles "too Long" entries already... I'll test it quickli when i have time. 
Until then, hear ya)

**Comment by MrCryptoT** [comment]
It seems as Im able again to watch Folders which are toop Long., 
I also tested the edit/add functionality of the ackupper... 
Seems to work... 
Can you confirm that this Basic functionality works (adding/editing folderpairs/timesettings) ? 

I have Holidays now for about a Week... So I'll certainly have some time to code a "bit" =) 

Have a good one bro - enjoy the summer Holiday break from School =)

**Comment by k-304** [comment]
Greate T0m!

Of course, i'll check this out, i just came back from Openair Frauenfeld, so i'll test it today after work (no holidays jet :/ ).

Have a nice week, enjoy the sun and do something for your "chällerbrüni"^^

**Comment by k-304** [comment]
So i'm testing it right now.
So far i found a small think wich seems to be unlogical in my opinion.
If you want to edit an backup entry in the settings form, the "Edit Dir" button is just not selectable.

See all my results later on:

UPDATE:
The automatic backup works fine. (Incr & Diff not?).
Log is also fine.
Editing times etc. also fine.

I'll implement a feature which shows a small message that backup has started / finished when the application is minimized to the system tray.

We should make the log box a bit bigger, it is a bit nasty.

**Comment by MrCryptoT** [comment]
The button isnot selectable because it has no function yet! 
(You can click but nothing happens) 
It s because the extra form to do that isn't programmed yet ;) =)

Haven't tested Incr/Diff ... Will test it and give my Feedback when done. 
Sry for the break by the way... Had some stressy Holidays. 

I think the log isn't writtena s afile yet - will fix that on time

Allright - sounds awesome. can't wait to see it =).

Yeah sure, make it bigger =) (even if we are not in Texas ;) )
We can also try to hide it or something... (IT writes a logfile - there is no Need for the txxtbox to be visible ;) )

**Comment by k-304** [comment]
Yea of course we can hide it and use it as a live "debug" feature... ;)
But it so we should place there something to show the users the backup is running... like a loading circle or something?

EDIT:
Will try to start SystemTray Messages today.

**Comment by MrCryptoT** [comment]
Well - I don't know a control like this... 
And I'm not sure if we can tetrieve a status of robocopy how far it is to update a progressbar... 
A circle may be better for the begging if such a control exists. (control is something like  a button etc - mayb i use the wrong word :3)
I'll write again when I could look at the incr/diff thing

**Comment by k-304** [comment]
Yea a circle would be great...

**Comment by MrCryptoT** [comment]
Allright - well let's have a look a this shall we ? 
http://www.codeproject.com/Articles/14841/How-to-write-a-loading-circle-animation-in-NET

**Comment by k-304** [comment]
Yea that looks nice... So lets take one of them... We need to check wich of them is the best for our design.

**Comment by MrCryptoT** [comment]
I leave that to U ;) You are the design guy :P
Will.have a look at incr and dif backup another day.
Hear u

**Comment by MrCryptoT** [comment]
ReGarding this issue - may I close it? 
Since the original Issue is fixxed...
Maybe open a new one for the backuptypes (full/incr/diff)...
When U test the next time please check if we can close an issue - on my side this one and the save-crash seem fixxed...
Have a good one!

**Comment by k-304** [comment]
Yep, I'll close this one.
The source Issue is fixxed.
