### ISSUE TITLE
Edit Time Configuration causes crash

### ISSUE THREAD

**Issue by k-304** [SnipeLike/WinBackupper#29]
Hi T0m

During my test of my new functions for the SystamTray Messages, I found one more bug.

When it happens:
1) Go to Settings Form
2) Select an entry and klick the Edit Time Config Button
3) Add 1 Time, save and Finish
4) Klick once more on the Edit Time Configuration Button and it should crash

Its an error in the "StringtoArray" function. I'd prefer if you can take a look.

**Comment by MrCryptoT** [comment]
On it.... 
You mentioned some changes which don't seem to be synced yet... 
I'll look into my fork, if i can reproduce it to search for the cause, I'll fix it in my fork and wait with syncing.. 
I'll note the lines I've changed so I'd be able to revert conflicts of changed code. 
So U can sync your changes first, and I'll sync and then implement the fix if thats ok. 
I'll try to code th whole evening so I should be able to fix some stuff.

**Comment by MrCryptoT** [comment]
So I tested this - but I think I don't quite understand how to reproduce it...
I tried to adding a time to the time config - closing the timeadd form (finish ) and then saving which will close both forms (Settings and timetable) via the save button.
reopen it and then do it again - it worked. 
Then I tried to just add a time, without the form closing (and therefore saving) by just clicking finish and closing the timetable form. then I reclicked the time config button to open timetable form added a time finished again and it worked. (it also saved etc.) 

BUT I found some other bugs of mine which I have fixxed.
I'm still testing and probably will find more - maybe I find that one too... 
Otherwise maybe U have to try it sometimes on my amchine ^^

**Comment by k-304** [comment]
Hmm.. So try to hit the finish Button and then save the settings form and open the Edit Time Form again... 
But maybe it is my not so fast computer at work... Some xmlWriter Problems maybe... I found another detail pointing on something like that...

Will test it on my home PC...

**Comment by MrCryptoT** [comment]
well i found something within the stringtoarray function but it  wa supposed to work like that (in the beginning) 
If you gve it an empty string ("") then it can't make an array. 
To prevent the error in the function, i coded that it would throw an exception and therfore "crash".
Now i recoded it so that it fills the array with "Nothing Configured" which is also shown to the user BUT NOT saved within the xml (hat would look damn ugly I think)
So if that was the problem, which I run into once too (so I guess I found it after trying 100 times xD) then it's fixxed. or it seems as it =). 
Im not sure if I should push the code though because you are working too... not that stupid conflicts come again... 

I really hope it s not a speed related issue... 
but for now it looks quite good

**Comment by k-304** [comment]
Nice and damn quick, great ;)

I think you can push it... I made only some small changes and I have to
delete the most of it anyway, because of the fact that I will create/edit
the TimeConfig Form.
So you're free to make a PR for my repo =)

Tom notifications@github.com schrieb am Do., 23. Juli 2015 um 21:31 Uhr:

**Comment by k-304** [comment]
Seems to work.
-CLOSED-
